version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://kurusampanst80:kurusampanst80@212.85.26.223:5432/kurusampanst80"
      PGRST_DB_SCHEMAS: "public"
      PGRST_DB_ANON_ROLE: "kurusampanst80"
