version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: >
        sh -c "python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn student_management_system.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./media:/app/media 
      - ./staticfiles:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media           # ให้ nginx เห็น media folder
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - default

networks:
  default:
    driver: bridge
